### ISSUE TITLE
AAD Connect Installation failing with a Set-MsolDirSyncEnabled error

### ISSUE THREAD

**Issue by SkillableBB** [MicrosoftLearning/MD-102T00-Microsoft-365-Endpoint-Administrator#63] opened 2023-08-16 22:31 UTC
### Step: 20 

Description of issue

On the Ready to configure page, ensure that Start the synchronization process when configuration completes is selected, and then select Install.
 
After clicking Install, then after a few seconds returns a Set-MsolDirSyncEnabled error [p1]. Investigating the error log further, it gives nodescript exception errors with text to try again later [p2]. We've also confirmed reports of this behavior occurring in other labs and WorkshopPLUS content, so it appears there may be an error on MSFT's end.

[p1] 

![image](https://github.com/MicrosoftLearning/MD-102T00-Microsoft-365-Endpoint-Administrator/assets/94069201/3b9b3bfe-0e29-4eda-bc85-e96e33e6a197)

[p2]

![image](https://github.com/MicrosoftLearning/MD-102T00-Microsoft-365-Endpoint-Administrator/assets/94069201/42d82a82-b730-4c46-9b42-410fdf939c71)

**Comment by craigbeeremct** [comment] 2023-08-17 02:56
All my students got this error on Monday. We all waited a bit and tried again, and the process worked, so I put it down to something about the short time between creating the tenant and installing ADConnect. Maybe that guess was not right?

**Comment by SkillableBB** [comment] 2023-08-17 18:28
We've been seeing it widespread on Skillable and still reproducing it with tenants in instances 24-48 hours after they've been created.

**Comment by mctniteshshukla** [comment] 2023-08-22 09:30
any update on this, it is urgent for us as none of the students are able to continue because this lab has a dependency on it.

**Comment by WigF1** [comment] 2023-08-22 22:23
This isn't a 'lab only' thing; it's a problem affecting anyone trying to install AADC. I did some digging in ILSpy at the underlying binaries and it seems like AADC merely imports the MSOnline module and invokes the same command you could do manually.

In ILSpy when looking at the MSOnline module, all the references are for API calls which are HTTP only and my money is on Microsoft disabling an endpoint that the MSOnline module calls, which in turn breaks our ability to change organisation configuration.

With regards not being able to continue @mctniteshshukla , you absolutely can continue. I am delivering the course this week. It does mean the following:

- Students won't be able to complete Lab 0102
- Students will need to skip Exercise 2 of Lab 0201
- Students will need to sign in as another user whenever they are promped to sign in as Aaron (I got mine to sign in as AlexW)
- Prior to Lab 0401, you will need to create a group in Entra that contains whichever user you are having students use instead of Aaron.
- Students won't be able to complete Lab 0502 (SSPR)

The other labs should work as intended.

**Comment by craigbeeremct** [comment] 2023-08-23 03:09
I have a student who has been trying the ADConnect ocasionally during this week. He reports that it worked as of about half an hour ago. I tried the install and it worked for me.
I've asked the rest of class to do the ADConnect lab at end-of-class today (in about an hour).

**Comment by WigF1** [comment] 2023-08-23 04:01
I just retried my install and it worked fine! Seems like someone at MS re-enabled the endpoint!

Thanks @craigbeeremct

**Comment by MSFT-rstearman** [comment] 2023-08-23 16:50
Last week we’ve learned that the Security Fraud team rolled out a patch for M365 trial tenants. This patch requires users to sign up using a credit card to validate their ID. Multiple content teams are impacted (not just use), that are dependent on these tenants. For us, this impacts our labs, New Credentials, and other areas that require an M365 tenant.

**Comment by WigF1** [comment] 2023-08-24 04:55
Interesting! Is this the likely cause of the issue? I saw on other forums that 'real' tenants were also affected.

**Comment by MSFT-rstearman** [comment] 2023-08-24 19:23
@WigF1 That is interesting. If you have info or examples of this issue spanning to non-test tenants, please provide some examples. All of our testing is showing that "real tenants" (non-test tenants) are not affected.

**Comment by MSFT-rstearman** [comment] 2023-09-12 19:00
Closing this out as it has been resolved.

**Closed by MSFT-rstearman** 2023-09-12 19:00 UTC
